// <auto-generated />
using CLMData.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace CLM.Infrastructure.Migrations
{
	[DbContext(typeof(CLMContext))]
	partial class CLMContextModelSnapshot : ModelSnapshot
	{
		protected override void BuildModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
				.HasAnnotation("Relational:MaxIdentifierLength", 128)
				.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

			modelBuilder.Entity("CLMData.Entity.Medico", b =>
				{
					b.Property<int>("MedicoId")
						.ValueGeneratedOnAdd()
						.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

					b.Property<string>("CRM")
						.HasColumnType("varchar(15)");

					b.Property<string>("Nome");

					b.HasKey("MedicoId");

					b.ToTable("Medico");
				});

			modelBuilder.Entity("CLMData.Entity.Paciente", b =>
				{
					b.Property<int>("PacienteId")
						.ValueGeneratedOnAdd()
						.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

					b.Property<string>("Nome")
						.HasColumnType("varchar(50)");

					b.Property<string>("Telefone");

					b.Property<string>("email")
						.HasColumnType("varchar(50)");

					b.HasKey("PacienteId");

					b.ToTable("Paciente");
				});
#pragma warning restore 612, 618
		}
	}
}